### ISSUE TITLE
compile flags are always set to the debug compilation values

### ISSUE THREAD

**Issue by rc-matthew-l-weber** [cpb-/spi-tools#12]
https://github.com/cpb-/spi-tools/blob/318bcae5249722873bf58b27afdd20473c7047cc/configure.ac#L76

This prevents flags from inheriting the provided CFLAGS value at compile time and instead always uses either "-g -Wall -Werror -Wno-uninitialized -O0" or "$AM_CFLAGS -O0" where $AM_CFLAGS is empty.

I believe a fix would be to make the non-debug case "-O0 CFLAGS" and similar for AM_CXXFLAGS so that a provided optimization would also override the -O0

**Comment by rc-matthew-l-weber** [comment]
[0001-spi-tools-observe-c-and-cxxflags-when-passed.txt](https://github.com/cpb-/spi-tools/files/2274548/0001-spi-tools-observe-c-and-cxxflags-when-passed.txt)

**Comment by cpb-** [comment]
Hello
Thank you for this remark. I've applied your modification.

**Comment by rc-matthew-l-weber** [comment]
This change was to support a build time hardening capability with compiler flags when the Buildroot buildsystem does a rootfs build.  When do you feel your next tag might be dropped so we could bump our version to a tag with this fix vs using a hash?
