### ISSUE TITLE
Minor typo in the documentation

### ISSUE THREAD

**Issue by moose-rivieh** [cpb-/spi-tools#24]
I believe the line
`$ printf '\x01\x82\F3' | spi-pipe -d /dev/spidev0.0 | hexdump -C`
should be
`$ printf '\x01\x82\xF3' | spi-pipe -d /dev/spidev0.0 | hexdump -C`

Just missing the 'x' for the last hex character.

**Comment by cpb-** [comment]
Applied. Thank you, Mustafa :-)
