### ISSUE TITLE
Tag 1.0.2 ?

### ISSUE THREAD

**Issue by adriweb** [cpb-/spi-tools#27]
Hello,

Could you release/tag the latest version from master as v1.0.2 so that we can use the latest `LSB_FIRST` fixes more easily?

Thanks :)

**Comment by cpb-** [comment]
Hello,
I pushed the 1.0.2 release a few seconds ago as 1748e092425a4a0ff693aa347062a57fc1ffdd00
Thank you for using spi-tools.

**Comment by adriweb** [comment]
Thank you !
