### ISSUE TITLE
Plain Makefile

### ISSUE THREAD

**Issue by biemster** [cpb-/spi-tools#30]
The use of conftools might be a bit overkill for a codebase this size, and complicates cross compiling (for me at least, I'm not very capable.) I compile this with a simple `Makefile` using the toolchain OpenWrt gives me after compiling firmware:
```Makefile
TOOLCHAIN = ..//openwrt-toolchain-ath79-generic_gcc-12.3.0_musl.Linux-x86_64/toolchain-mips_24kc_gcc-12.3.0_musl
CC = $(TOOLCHAIN)/bin/mips-openwrt-linux-musl-gcc

default: all

spi-config:
	mkdir -p bin
	echo "#define VERSION 0" > src/config.h
	$(CC) -s -march=24kc -ffreestanding src/spi-config.c src/spi-tools.c -I src -Wall -Os -o bin/spi-config

spi-pipe:
	mkdir -p bin
	echo "#define VERSION 0" > src/config.h
	$(CC) -s -march=24kc -ffreestanding src/spi-pipe.c src/spi-tools.c -I src -Wall -Os -o bin/spi-pipe

all: spi-config spi-pipe

clean:
	rm -r bin

```
This should make it a bit more straightforward to experiment with the compiler options, if needed.

**Comment by cpb-** [comment]
Hi,

Thank you for this comment.

I don't know much bout OpenWRT but I think a recipe already exists in the packages base: [spi-tools](https://openwrt.org/packages/pkgdata/spi-tools)

This way, you won't ever need to write yourself the Makefile  :-)

**Comment by biemster** [comment]
Ha! How did I miss that? You can close this issue, although it has uses outside of openwrt as well of course.
