### ISSUE TITLE
Intégration de spi-tools à Yocto

### ISSUE THREAD

**Issue by texierp** [cpb-/spi-tools#4]
J'ai en prévision d'intégrer l'outils à Yocto (déjà opérationnel en local) sur la meta-raspberry, c'est ok pour toi ?

**Comment by cpb-** [comment]
Bonjour,
Oui bien sûr. Merci.

**Comment by texierp** [comment]
Bonjour,

Super, merci

**Comment by texierp** [comment]
Bonjour Christophe,

Pour info 'spitools' est officiellement intégré à Yocto/OE : https://github.com/openembedded/meta-oe/blob/master/meta-oe/recipes-support/spitools/spitools_git.bb

A+

**Comment by cpb-** [comment]
C'est cool

## Merci.

C.B
Le 13 avr. 2015 20:18, "Pierre-jean TEXIER" notifications@github.com a
écrit :

**Comment by texierp** [comment]
Avec plaisir ;)
