### ISSUE TITLE
tag version with autotools support

### ISSUE THREAD

**Issue by enunes** [cpb-/spi-tools#7]
Hi cpb-,

I have recently included a recipe for spi-tools in Buildroot:
https://patchwork.ozlabs.org/patch/547120/

We are currently fetching from the commit sha1 which currently points to the tip of the master branch, as there is no tagged version with autotools support.

I have submitted today two pull requests in order to fix two issues found with spi-tools since its inclusion in Buildroot. One is related to the build problem with musl as seen in:
http://autobuild.buildroot.net/results/ed8/ed89fae4a722b5d2adff9826bb88e55e58af77f6/
The other is related to the GIT_VERSION variable as can be seen in the patch mentioned in the beginning.

I'm opening this issue in order to suggest that a new version gets tagged in case you agree with the pull requests. I see that the autotools scripts already point to a 0.8.1 version but there is no tag to this version yet.
If you are able to generate a tag to this new version with autotools support and these fixes, I can then send a version update to Buildroot to this new tagged version, which will fix all of the mentioned issues without "out-of-tree" patches/hacks, and also setting its version to something more pretty than a commit sha1.

Thanks for spi-tools and for your attention.

Erico

**Comment by cpb-** [comment]
Hi,

Thanks for your pull requests. I merged them.
I also generated a 0.8.1 tag.

Thanks a lot.
